

/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#ifndef	_ALL_V2X_USERS_SCHEDULING_PLMN_H_
#define	_ALL_V2X_USERS_SCHEDULING_PLMN_H_


#include <asn_application.h>

/* Including external dependencies */
// #include <asn_SEQUENCE.h>

#include "PLMN-Identity.h"
#include <constr_SEQUENCE.h>
// #include "V2X-Scheduling-All-Users.h"


#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */

struct V2X_Scheduling_All_Users;

typedef struct V2X_Scheduling_All_UsersPlmn {
	PLMN_Identity_t plmn_id;
	struct V2X_Scheduling_All_Users* v2XSchedulingAllUsersList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} V2X_Scheduling_All_UsersPlmn_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_V2X_Scheduling_All_UsersPlmn;
// extern asn_SET_OF_specifics_t asn_SPC_V2X_Scheduling_All_Users_specs_1;
extern asn_SEQUENCE_specifics_t asn_SPC_V2X_Scheduling_All_UsersPlmn_specs_1;
extern asn_TYPE_member_t asn_MBR_V2X_Scheduling_All_UsersPlmn_1[2];
// extern asn_per_constraints_t asn_PER_type_V2X_Scheduling_All_UsersPlmn_constr_1; 

#ifdef __cplusplus
}
#endif

#endif	/* _ALL_V2X_USERS_SCHEDULING_PLMN_H_ */
#include <asn_internal.h>
