/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#ifndef	_E2SM_RC_ControlMessage_H_
#define	_E2SM_RC_ControlMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2SM_RC_ControlMessage_PR {
	E2SM_RC_ControlMessage_PR_NOTHING,	/* No components present */
	E2SM_RC_ControlMessage_PR_controlMessage_Format1,
	/* Extensions may appear below */
	// modified
	E2SM_RC_ControlMessage_PR_handoverMessage_Format
	// end modification
	
} E2SM_RC_ControlMessage_PR;

/* Forward declarations */
struct E2SM_RC_ControlMessage_Format1;
// modified
struct AllHandoversListPlmn;
// end modification

/* E2SM-RC-ControlMessage */
typedef struct E2SM_RC_ControlMessage {
	E2SM_RC_ControlMessage_PR present;
	union E2SM_RC_ControlMessage_u {
		struct E2SM_RC_ControlMessage_Format1	*controlMessage_Format1;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		// modified
		struct AllHandoversListPlmn *handoverMessage_Format;
		// end modification
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_RC_ControlMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_RC_ControlMessage;
// modified
// extern asn_CHOICE_specifics_t asn_SPC_E2SM_RC_ControlMessage_specs_1;
// extern asn_TYPE_member_t asn_MBR_E2SM_RC_ControlMessage_1[2];
// extern asn_per_constraints_t asn_PER_type_E2SM_RC_ControlMessage_constr_1;
// end modification

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_RC_ControlMessage_H_ */
#include <asn_internal.h>
