/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "E2AP-PDU-Contents-v01.00.asn"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_V2X_Scheduling_All_Users_H_
#define	_V2X_Scheduling_All_Users_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
// struct V2X_Scheduling_User;
struct V2X_Scheduling_Source;

/* RICaction-NotAdmitted-List */
typedef struct V2X_Scheduling_All_Users {
	// A_SEQUENCE_OF(struct V2X_Scheduling_User) list;
	A_SEQUENCE_OF(struct V2X_Scheduling_Source) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} V2X_Scheduling_All_Users_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_V2X_Scheduling_All_Users;
extern asn_SET_OF_specifics_t asn_SPC_V2X_Scheduling_All_Users_specs_1;
extern asn_TYPE_member_t asn_MBR_V2X_Scheduling_All_Users_1[1];
// extern asn_per_constraints_t asn_PER_type_V2X_Scheduling_All_Users_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _V2X_Scheduling_All_Users_H_ */
#include <asn_internal.h>
