/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#ifndef	_V2X_Scheduling_Item_H_
#define	_V2X_Scheduling_Item_H_


#include <asn_application.h>

/* Including external dependencies */
// #include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>
#include <Buffer-String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UE-Identity */

/* V2X_Scheduling_Item */
typedef struct V2X_Scheduling_Item {
	Buffer_String_t	nrSlotAllocBuffer;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} V2X_Scheduling_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_V2X_Scheduling_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_V2X_Scheduling_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_V2X_Scheduling_Item_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _V2X_Scheduling_Item_H_ */
#include <asn_internal.h>
