/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#include "V2X-Single-User-report.h"

#include "V2XSciMessageItem-List.h"
#include "V2XAllBufferPacketDelays.h"

asn_TYPE_member_t asn_MBR_V2X_Single_User_Report_1[] = {
	
	{ ATF_NOFLAGS, 0, offsetof(struct V2X_Single_User_Report, xPosition),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeReal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"xPosition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct V2X_Single_User_Report, yPosition),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeReal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"yPosition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct V2X_Single_User_Report, userBufferDelayList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* EXPLICIT tag at current level */
		&asn_DEF_V2XAllBufferPacketDelays,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"userBufferDelayList"
		},
	// { ATF_NOFLAGS, 0, offsetof(struct V2X_Single_User_Report, userReceivedSciMessages),
	// 	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	// 	-1,	/* EXPLICIT tag at current level */
	// 	&asn_DEF_V2XSciMessageItemList,
	// 	0,
	// 	{ 0, 0, 0 },
	// 	0, 0, /* No default value */
	// 	"userReceivedSciMessages"
	// 	},
	// { ATF_POINTER, 1, offsetof(struct V2X_Single_User_Report, userBufferDelayList),
	// 	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	// 	-1,	/* EXPLICIT tag at current level */
	// 	&asn_DEF_V2XAllBufferPacketDelays,
	// 	0,
	// 	{ 0, 0, 0 },
	// 	0, 0, /* No default value */
	// 	"userBufferDelayList"
	// 	},
	{ ATF_POINTER, 1, offsetof(struct V2X_Single_User_Report, userReceivedSciMessages),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* EXPLICIT tag at current level */
		&asn_DEF_V2XSciMessageItemList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"userReceivedSciMessages"
		},
};
static const int asn_MAP_V2X_Single_User_Report_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_V2X_Single_User_Report_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_V2X_Single_User_Report_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* userBufferDelayList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* userReceivedSciMessages */
	{ (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* xPosition */
	{ (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* yPosition */
};
// asn_SEQUENCE_specifics_t asn_SPC_V2X_Single_User_Report_specs_1 = {
// 	sizeof(struct V2X_Single_User_Report),
// 	offsetof(struct V2X_Single_User_Report, _asn_ctx),
// 	asn_MAP_V2X_Single_User_Report_tag2el_1,
// 	3,	/* Count of tags in the map */
// 	// asn_MAP_V2X_Single_User_Repor0t_oms_1,	/* Optional members */
// 	0,	/* Optional members */
// 	// 2, 0,	/* Root/Additions */
// 	0, 0,	/* Root/Additions */
// 	3,	/* First extension addition */
// };
asn_SEQUENCE_specifics_t asn_SPC_V2X_Single_User_Report_specs_1 = {
	sizeof(struct V2X_Single_User_Report),
	offsetof(struct V2X_Single_User_Report, _asn_ctx),
	asn_MAP_V2X_Single_User_Report_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_V2X_Single_User_Report_oms_1,	/* Optional members */
	// 0,	/* Optional members */
	1, 0,	/* Root/Additions */
	// 0, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_V2X_Single_User_Report = {
	"V2X-Single-User-Report",
	"V2X-Single-User-Report",
	&asn_OP_SEQUENCE,
	asn_DEF_V2X_Single_User_Report_tags_1,
	sizeof(asn_DEF_V2X_Single_User_Report_tags_1)
		/sizeof(asn_DEF_V2X_Single_User_Report_tags_1[0]), /* 1 */
	asn_DEF_V2X_Single_User_Report_tags_1,	/* Same as above */
	sizeof(asn_DEF_V2X_Single_User_Report_tags_1)
		/sizeof(asn_DEF_V2X_Single_User_Report_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_V2X_Single_User_Report_1,
	4,	/* Elements count */
	// 2,	/* Elements count */
	&asn_SPC_V2X_Single_User_Report_specs_1	/* Additional specs */
};

