/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#ifndef	_V2XAllBufferPacketDelays_H_
#define	_V2XAllBufferPacketDelays_H_


#include <asn_application.h>

/* Including external dependencies */
#include "V2XId.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

// #include "V2XSciMessageItem-List.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct V2XBufferPacketDelays;

/* V2XAllBufferPacketDelays */
typedef struct V2XAllBufferPacketDelays {
	V2XId_t	 v2xNodeId;
	struct V2XAllBufferPacketDelays__V2XBufferPacketDelaysList {
		A_SEQUENCE_OF(struct V2XBufferPacketDelays) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} V2XBufferPacketDelaysList;

	// V2XSciMessageItemList_t	userReceivedSciMessages;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} V2XAllBufferPacketDelays_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_V2XAllBufferPacketDelays;
extern asn_SEQUENCE_specifics_t asn_SPC_V2XAllBufferPacketDelays_specs_1;
extern asn_TYPE_member_t asn_MBR_V2XAllBufferPacketDelays_1[2];
// extern asn_TYPE_member_t asn_MBR_V2XAllBufferPacketDelays_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _V2XAllBufferPacketDelays_H_ */
#include <asn_internal.h>
