/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "E2AP-PDU-Contents-v01.00.asn"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#include "V2XAllUsersBufferDelayReports.h"
#include "V2XAllBufferPacketDelays.h"

static asn_oer_constraints_t asn_OER_type_V2XAllUsersBufferDelayReports_constr_1 CC_NOTUSED = {
	{ 2, 0 },
	-1	/* (SIZE(0..1023)) */};
asn_per_constraints_t asn_PER_type_V2XAllUsersBufferDelayReports_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  1023 }	/* (SIZE(0..16)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_V2XAllUsersBufferDelayReports_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_V2XAllBufferPacketDelays,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"allUsersBufferDelayReports"
		},
};
static const ber_tlv_tag_t asn_DEF_V2XAllUsersBufferDelayReports_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_V2XAllUsersBufferDelayReports_specs_1 = {
	sizeof(struct V2XAllUsersBufferDelayReports),
	offsetof(struct V2XAllUsersBufferDelayReports, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_V2XAllUsersBufferDelayReports = {
	"V2X-All-Users-Buffer-Delay-Reports",
	"V2X-All-Users-Buffer-Delay-Reports",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_V2XAllUsersBufferDelayReports_tags_1,
	sizeof(asn_DEF_V2XAllUsersBufferDelayReports_tags_1)
		/sizeof(asn_DEF_V2XAllUsersBufferDelayReports_tags_1[0]), /* 1 */
	asn_DEF_V2XAllUsersBufferDelayReports_tags_1,	/* Same as above */
	sizeof(asn_DEF_V2XAllUsersBufferDelayReports_tags_1)
		/sizeof(asn_DEF_V2XAllUsersBufferDelayReports_tags_1[0]), /* 1 */
	{ &asn_OER_type_V2XAllUsersBufferDelayReports_constr_1, &asn_PER_type_V2XAllUsersBufferDelayReports_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_V2XAllUsersBufferDelayReports_1,
	1,	/* Single element */
	&asn_SPC_V2XAllUsersBufferDelayReports_specs_1	/* Additional specs */
};

