/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#include "V2XBufferPacketDelays.h"

#include "V2XPacketDelayInterval.h"

#include "V2XHarqBufferSize.h"

static int
memb_v2XPacketDelayIntervalList_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 0 && size <= 65535)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_V2XHarqBufferSizeList_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 0 && size <= 65535)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}


// static asn_oer_constraints_t asn_OER_type_v2XPacketDelayIntervalList_constr_3 CC_NOTUSED = {
// 	{ 2, 0 },
// 	-1	/* (SIZE(1..64)) */};
static asn_per_constraints_t asn_PER_type_v2XPacketDelayIntervalList_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(1..64)) */,
	0, 0	/* No PER value map */
};
// static asn_oer_constraints_t asn_OER_memb_v2XPacketDelayIntervalList_constr_3 CC_NOTUSED = {
// 	{ 2, 0 },
// 	-1	/* (SIZE(1..64)) */};
static asn_per_constraints_t asn_PER_memb_v2XPacketDelayIntervalList_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(1..64)) */,
	0, 0	/* No PER value map */
};

// static asn_oer_constraints_t asn_OER_type_V2XHarqBufferSizeList_constr_3 CC_NOTUSED = {
// 	{ 2, 0 },
// 	-1	/* (SIZE(1..1023)) */};
static asn_per_constraints_t asn_PER_type_V2XHarqBufferSizeList_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(1..1023)) */,
	0, 0	/* No PER value map */
};
// static asn_oer_constraints_t asn_OER_memb_V2XHarqBufferSizeList_constr_3 CC_NOTUSED = {
// 	{ 2, 0 },
// 	-1	/* (SIZE(1..1023)) */};
static asn_per_constraints_t asn_PER_memb_V2XHarqBufferSizeList_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(1..1023)) */,
	0, 0	/* No PER value map */
};


static asn_TYPE_member_t asn_MBR_v2XPacketDelayIntervalList_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_V2XPacketDelayInterval,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v2XPacketDelayIntervalList"
		},
};

static asn_TYPE_member_t asn_MBR_V2XHarqBufferSizeList_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_V2XHarqBufferSize,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v2XHarqBufferSizeList"
		},
};

static const ber_tlv_tag_t asn_DEF_v2XPacketDelayIntervalList_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};

static const ber_tlv_tag_t asn_DEF_V2XHarqBufferSizeList_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};

static asn_SET_OF_specifics_t asn_SPC_v2XPacketDelayIntervalList_specs_3 = {
	sizeof(struct V2XBufferPacketDelays__V2XPacketDelayIntervalList),
	offsetof(struct V2XBufferPacketDelays__V2XPacketDelayIntervalList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};

static asn_SET_OF_specifics_t asn_SPC_V2XHarqBufferSizeList_specs_3 = {
	sizeof(struct V2XBufferPacketDelays__V2XHarqBufferSizeList),
	offsetof(struct V2XBufferPacketDelays__V2XHarqBufferSizeList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};


static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v2XPacketDelayIntervalList_3 = {
	"V2XPacketDelayIntervalList",
	"V2XPacketDelayIntervalList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_v2XPacketDelayIntervalList_tags_3,
	sizeof(asn_DEF_v2XPacketDelayIntervalList_tags_3)
		/sizeof(asn_DEF_v2XPacketDelayIntervalList_tags_3[0]) - 1, /* 1 */
	asn_DEF_v2XPacketDelayIntervalList_tags_3,	/* Same as above */
	sizeof(asn_DEF_v2XPacketDelayIntervalList_tags_3)
		/sizeof(asn_DEF_v2XPacketDelayIntervalList_tags_3[0]), /* 2 */
	{ 0, &asn_PER_type_v2XPacketDelayIntervalList_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_v2XPacketDelayIntervalList_3,
	1,	/* Single element */
	&asn_SPC_v2XPacketDelayIntervalList_specs_3	/* Additional specs */
};

static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_V2XHarqBufferSizeList_3 = {
	"V2XHarqBufferSizeList",
	"V2XHarqBufferSizeList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_V2XHarqBufferSizeList_tags_3,
	sizeof(asn_DEF_V2XHarqBufferSizeList_tags_3)
		/sizeof(asn_DEF_V2XHarqBufferSizeList_tags_3[0]) - 1, /* 1 */
	asn_DEF_V2XHarqBufferSizeList_tags_3,	/* Same as above */
	sizeof(asn_DEF_V2XHarqBufferSizeList_tags_3)
		/sizeof(asn_DEF_V2XHarqBufferSizeList_tags_3[0]), /* 2 */
	{ 0, &asn_PER_type_V2XHarqBufferSizeList_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_V2XHarqBufferSizeList_3,
	1,	/* Single element */
	&asn_SPC_V2XHarqBufferSizeList_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_V2XBufferPacketDelays_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct V2XBufferPacketDelays, v2xNodeId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_V2XId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v2xNodeId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct V2XBufferPacketDelays, v2XPacketDelayIntervalList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v2XPacketDelayIntervalList_3,
		0,
		{ 0, &asn_PER_memb_v2XPacketDelayIntervalList_constr_3,  memb_v2XPacketDelayIntervalList_constraint_1 },
		0, 0, /* No default value */
		"v2XPacketDelayIntervalList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct V2XBufferPacketDelays, v2XHarqBufferSizeList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_V2XHarqBufferSizeList_3,
		0,
		{ 0, &asn_PER_memb_V2XHarqBufferSizeList_constr_3,  memb_V2XHarqBufferSizeList_constraint_1 },
		0, 0, /* No default value */
		"v2XHarqBufferSizeList"
		},
};
static const ber_tlv_tag_t asn_DEF_V2XBufferPacketDelays_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_V2XBufferPacketDelays_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* v2xNodeId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* v2XPacketDelayIntervalList */
	{ (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* V2XHarqBufferSizeList */
};
asn_SEQUENCE_specifics_t asn_SPC_V2XBufferPacketDelays_specs_1 = {
	sizeof(struct V2XBufferPacketDelays),
	offsetof(struct V2XBufferPacketDelays, _asn_ctx),
	asn_MAP_V2XBufferPacketDelays_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_V2XBufferPacketDelays = {
	"V2XBufferPacketDelays",
	"V2XBufferPacketDelays",
	&asn_OP_SEQUENCE,
	asn_DEF_V2XBufferPacketDelays_tags_1,
	sizeof(asn_DEF_V2XBufferPacketDelays_tags_1)
		/sizeof(asn_DEF_V2XBufferPacketDelays_tags_1[0]), /* 1 */
	asn_DEF_V2XBufferPacketDelays_tags_1,	/* Same as above */
	sizeof(asn_DEF_V2XBufferPacketDelays_tags_1)
		/sizeof(asn_DEF_V2XBufferPacketDelays_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_V2XBufferPacketDelays_1,
	3,	/* Elements count */
	&asn_SPC_V2XBufferPacketDelays_specs_1	/* Additional specs */
};

