/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "E2AP-IEs-v01.00.asn"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#include "V2XPacketDelayInterval.h"

static int
memb_lowerInterval_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 4294967295)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_upperInterval_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 4294967295)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_numberOfPackets_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 4294967295)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_reservationPeriod_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_bufferSize_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 4294967295)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

// static asn_oer_constraints_t asn_OER_memb_lowerInterval_constr_2 CC_NOTUSED = {
// 	{ 4, 1 }	/* (0..65535) */,
// 	-1};
static asn_per_constraints_t asn_PER_memb_lowerInterval_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32,  32,  0,  4294967295 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
// static asn_oer_constraints_t asn_OER_memb_upperInterval_constr_3 CC_NOTUSED = {
// 	{ 4, 1 }	/* (0..65535) */,
// 	-1};
static asn_per_constraints_t asn_PER_memb_upperInterval_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32,  32,  0,  4294967295 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};

// static asn_oer_constraints_t asn_OER_memb_numberOfPackets_constr_4 CC_NOTUSED = {
// 	{ 4, 1 }	/* (0..4294967295) */,
// 	-1};
static asn_per_constraints_t asn_PER_memb_numberOfPackets_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32,  32,  0,  4294967295 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};

// static asn_oer_constraints_t asn_OER_memb_reservationPeriod_constr_5 CC_NOTUSED = {
// 	{ 2, 1 }	/* (0..1000) */,
// 	-1};
static asn_per_constraints_t asn_PER_memb_reservationPeriod_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..1000) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};

// static asn_oer_constraints_t asn_OER_memb_bufferSize_constr_6 CC_NOTUSED = {
// 	{ 4, 1 }	/* (0..4294967295) */,
// 	-1};
static asn_per_constraints_t asn_PER_memb_bufferSize_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32,  32,  0,  4294967295 }	/* (0..1000) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};

asn_TYPE_member_t asn_MBR_V2XPacketDelayInterval_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct V2XPacketDelayInterval, lowerInterval),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_lowerInterval_constr_2,  memb_lowerInterval_constraint_1 },
		0, 0, /* No default value */
		"lowerInterval"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct V2XPacketDelayInterval, upperInterval),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_upperInterval_constr_3,  memb_upperInterval_constraint_1 },
		0, 0, /* No default value */
		"upperInterval"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct V2XPacketDelayInterval, numberOfPackets),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_numberOfPackets_constr_4,  memb_numberOfPackets_constraint_1 },
		0, 0, /* No default value */
		"numberOfPackets"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct V2XPacketDelayInterval, reservationPeriod),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_reservationPeriod_constr_5,  memb_reservationPeriod_constraint_1 },
		0, 0, /* No default value */
		"reservationPeriod"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct V2XPacketDelayInterval, bufferSize),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_bufferSize_constr_6,  memb_bufferSize_constraint_1 },
		0, 0, /* No default value */
		"bufferSize"
		},
};
static const ber_tlv_tag_t asn_DEF_V2XPacketDelayInterval_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)) 
};
static const asn_TYPE_tag2member_t asn_MAP_V2XPacketDelayInterval_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* lowerInterval */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* upperInterval */
	{ (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* numberOfPackets */
	{ (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* reservationPeriod */
	{ (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* bufferSize */
};
asn_SEQUENCE_specifics_t asn_SPC_V2XPacketDelayInterval_specs_1 = {
	sizeof(struct V2XPacketDelayInterval),
	offsetof(struct V2XPacketDelayInterval, _asn_ctx),
	asn_MAP_V2XPacketDelayInterval_tag2el_1,
	// 4,	/* Count of tags in the map */
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	// 4,	/* First extension addition */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_V2XPacketDelayInterval = {
	"V2XPacketDelayInterval",
	"V2XPacketDelayInterval",
	&asn_OP_SEQUENCE,
	asn_DEF_V2XPacketDelayInterval_tags_1,
	sizeof(asn_DEF_V2XPacketDelayInterval_tags_1)
		/sizeof(asn_DEF_V2XPacketDelayInterval_tags_1[0]), /* 1 */
	asn_DEF_V2XPacketDelayInterval_tags_1,	/* Same as above */
	sizeof(asn_DEF_V2XPacketDelayInterval_tags_1)
		/sizeof(asn_DEF_V2XPacketDelayInterval_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_V2XPacketDelayInterval_1,
	// 4,	/* Elements count */
	5,	/* Elements count */
	&asn_SPC_V2XPacketDelayInterval_specs_1	/* Additional specs */
};

