/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "E2AP-IEs-v01.00.asn"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#include "V2XSciMessageItem.h"

asn_TYPE_member_t asn_MBR_V2XSciMessageItem_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct V2XSciMessageItem, rsrp),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeReal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rsrp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct V2XSciMessageItem, header),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Buffer_String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"header"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct V2XSciMessageItem, tag),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Buffer_String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tag"
		},
	// { ATF_POINTER, 2, offsetof(struct V2XSciMessageItem, header),
	// 	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	// 	-1,	/* IMPLICIT tag at current level */
	// 	&asn_DEF_Buffer_String,
	// 	0,
	// 	{ 0, 0, 0 },
	// 	0, 0, /* No default value */
	// 	"header"
	// 	},
	// { ATF_POINTER, 1, offsetof(struct V2XSciMessageItem, tag),
	// 	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	// 	-1,	/* IMPLICIT tag at current level */
	// 	&asn_DEF_Buffer_String,
	// 	0,
	// 	{ 0, 0, 0 },
	// 	0, 0, /* No default value */
	// 	"tag"
	// 	},
	
};
static const int asn_MAP_PerQCIReportListItemFormat_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_V2XSciMessageItem_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_V2XSciMessageItem_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* lowerInterval */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* upperInterval */
	{ (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* rsrp */
};
asn_SEQUENCE_specifics_t asn_SPC_V2XSciMessageItem_specs_1 = {
	sizeof(struct V2XSciMessageItem),
	offsetof(struct V2XSciMessageItem, _asn_ctx),
	asn_MAP_V2XSciMessageItem_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
// asn_SEQUENCE_specifics_t asn_SPC_V2XSciMessageItem_specs_1 = {
// 	sizeof(struct V2XSciMessageItem),
// 	offsetof(struct V2XSciMessageItem, _asn_ctx),
// 	asn_MAP_V2XSciMessageItem_tag2el_1,
// 	3,	/* Count of tags in the map */
// 	// 0, 
// 	// 0, 0,	/* Optional elements (not needed) */
// 	asn_MAP_PerQCIReportListItemFormat_oms_1,
// 	2, 0,	/* Root/Additions */
// 	3,	/* First extension addition */
// };
asn_TYPE_descriptor_t asn_DEF_V2XSciMessageItem = {
	"V2XSciMessageItem",
	"V2XSciMessageItem",
	&asn_OP_SEQUENCE,
	asn_DEF_V2XSciMessageItem_tags_1,
	sizeof(asn_DEF_V2XSciMessageItem_tags_1)
		/sizeof(asn_DEF_V2XSciMessageItem_tags_1[0]), /* 1 */
	asn_DEF_V2XSciMessageItem_tags_1,	/* Same as above */
	sizeof(asn_DEF_V2XSciMessageItem_tags_1)
		/sizeof(asn_DEF_V2XSciMessageItem_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_V2XSciMessageItem_1,
	3,	/* Elements count */
	&asn_SPC_V2XSciMessageItem_specs_1	/* Additional specs */
};

